Repository codestates-seb/seb40_main_022, pull requests merged in 2022-12, with the labels that each got.

#125 [FE]Feat/QnA 페이징+CSS 수정
  client/.gitignore
  client/package.json
  client/src/pages/main/MainStyle.jsx
  client/src/pages/qna/Pagination.jsx
  client/src/pages/qna/QnaList.jsx
  client/src/pages/qna/QnaStyle.jsx
  client/src/pages/signup/SignUp.jsx
  client/src/redux/action/QnaAsync.jsx
  client/src/redux/reducer/QnaSlice.jsx
Labels: 🌟Feature, FrontEnd

#126 [Fe]Err/refac
  client/.gitignore
  client/data.json
  client/package.json
  client/src/components/modal/ChallengeReq.jsx
  client/src/components/ouath/Ouaths.jsx
  client/src/pages/calendar/Calendar.jsx
  client/src/pages/calendar/Detail.jsx
  client/src/pages/calendar/Style.jsx
  client/src/pages/lank/Lank.jsx
  client/src/pages/lank/LankContent.jsx
  client/src/pages/lank/LankDropdown.jsx
  client/src/pages/main/DailyPost.jsx
  client/src/pages/mypage/PictureBox.jsx
  client/src/pages/userprofile/userPicture.jsx
  client/src/redux/action/LankAsync.jsx
  client/src/redux/action/LoginAsync.jsx
  client/src/redux/action/MainAsync.jsx
  client/src/redux/action/MypageAsync.jsx
  client/src/redux/action/MypageEditAsync.jsx
  client/src/redux/action/ProfileAsync.jsx
  client/src/redux/action/QnaAsync.jsx
  client/src/redux/action/RecordAsync.jsx
  client/src/redux/action/SignupAsync.jsx
  client/src/redux/reducer/LankSlice.jsx
  client/src/redux/reducer/RecordSlice.jsx
Labels: 🤬BugFix, 🖥Deploy, 🏭Refactor

#128 [FE] 오류및 css수정
  client/src/pages/calendar/Calendar.jsx
  client/src/pages/calendar/Detail.jsx
  client/src/pages/calendar/Style.jsx
  client/src/pages/lank/LankContent.jsx
  client/src/pages/login/Login.jsx
  client/src/pages/main/Main.jsx
  client/src/pages/main/MainStyle.jsx
  client/src/pages/qna/QnaList.jsx
  client/src/pages/signup/SignUp.jsx
  client/src/redux/action/LoginAsync.jsx
  client/src/redux/action/RecordAsync.jsx
  client/src/redux/action/SignupAsync.jsx
  client/src/redux/reducer/LankSlice.jsx
  client/src/redux/reducer/MypageSlice.jsx
  client/src/redux/reducer/ProfileSlice.jsx
  client/src/redux/reducer/QnaSlice.jsx
  client/src/redux/reducer/RecordSlice.jsx
Labels: 🎨CSS, 🖥Deploy, 🌟Feature, 🏭Refactor, FrontEnd

#132 [FE] 대결 모달 수정 + 댓글 수정
  client/src/components/header/Head.jsx
  client/src/components/modal/Challenge.jsx
  client/src/components/modal/ChallengeReq.jsx
  client/src/components/modal/modalstyle.jsx
  client/src/pages/lank/LankDropdown.jsx
  client/src/pages/main/DailyCmt.jsx
  client/src/pages/main/DailyImg.jsx
  client/src/pages/main/DailyPost.jsx
  client/src/pages/main/MainInside.jsx
  client/src/pages/main/MainStyle.jsx
Labels: 🌟Feature, FrontEnd

#133 [FE] Err/refac
  client/src/components/modal/Challenge.jsx
  client/src/images/Profile.png
  client/src/pages/calendar/Calendar.jsx
  client/src/pages/calendar/Detail.jsx
  client/src/pages/calendar/Update.jsx
  client/src/pages/lank/LankContent.jsx
  client/src/pages/lank/LankContentstyle.jsx
  client/src/pages/mypage/Mypage.jsx
  client/src/pages/profileedit/index.jsx
Labels: 🌟Feature, 🏭Refactor, FrontEnd

#134 [FE]mockup 추가- 지울예정
  client/src/images/mockupProfile.png
  client/src/pages/main/DailyCmt.jsx
  client/src/pages/main/DailyPost.jsx
  client/src/pages/main/MainStyle.jsx
Labels: FrontEnd

#135 [FE] Err/refac
  client/src/components/modal/Challenge.jsx
  client/src/pages/lank/LankContent.jsx
  client/src/pages/mypage/Mypage.jsx
Labels: 🌟Feature, 🏭Refactor, FrontEnd

#136 [FE] 캘린더 css 완료
  client/src/components/modal/ChallengeReq.jsx
  client/src/pages/calendar/Calendar.jsx
  client/src/pages/calendar/Detail.jsx
  client/src/pages/calendar/Style.jsx
  client/src/pages/calendar/Update.jsx
  client/src/pages/lank/LankContent.jsx
  client/src/pages/qna/QnaDetail.jsx
  client/src/pages/qna/QnaList.jsx
  client/src/redux/action/QnaAsync.jsx
  client/src/redux/action/RecordAsync.jsx
  client/src/redux/reducer/QnaSlice.jsx
Labels: 🌟Feature, 🏭Refactor, FrontEnd

#137 [FE] err/refac
  client/src/pages/lank/LankContent.jsx
Labels: 🌟Feature, 🏭Refactor, FrontEnd

#138 [FE]랭킹 서치수정
  client/src/components/modal/noticeModal.jsx
  client/src/pages/lank/LankContent.jsx
  client/src/pages/lank/LankContentstyle.jsx
  client/src/redux/action/LankAsync.jsx
Labels: 🌟Feature, 🏭Refactor, FrontEnd

#139 [FE] merge: 병합
  client/src/pages/mypage/Mypage.jsx
  client/src/pages/profileedit/index.jsx
  client/src/pages/userprofile/index.jsx
Labels: 🏭Refactor, FrontEnd

#140 [FE]Feat/main crud
  client/src/components/modal/ChallengeReq.jsx
  client/src/components/modal/noticeModal.jsx
  client/src/pages/main/DailyCmt.jsx
  client/src/pages/main/DailyPost.jsx
  client/src/pages/main/MainStyle.jsx
  client/src/pages/profileedit/index.jsx
  client/src/pages/qna/QnaDetail.jsx
  client/src/redux/action/MypageAsync.jsx
Labels: FrontEnd

#141 [FE] Err/refac - uuid집어넣기
  client/package-lock.json
  client/package.json
  client/src/components/modal/noticeModal.jsx
  client/src/pages/calendar/Calendar.jsx
  client/src/pages/calendar/Detail.jsx
  client/src/pages/calendar/Update.jsx
  client/src/pages/dailypost/DailyEdit.jsx
  client/src/pages/dailypost/dailypost.jsx
  client/src/pages/lank/LankContent.jsx
  client/src/pages/main/DailyCmt.jsx
  client/src/pages/main/DailyImg.jsx
  client/src/pages/main/DailyInfo.jsx
  client/src/pages/main/DailyPost.jsx
  client/src/pages/mypage/Mypage.jsx
  client/src/pages/mypage/PictureBox.jsx
  client/src/pages/profileedit/index.jsx
  client/src/pages/qna/QnaAsk.jsx
  client/src/pages/qna/QnaDetail.jsx
  client/src/redux/action/LankAsync.jsx
  client/src/redux/action/MypageAsync.jsx
Labels: 🌟Feature, 🏭Refactor, FrontEnd

#143 [FE] Qna수정
  client/src/components/header/Header.jsx
  client/src/components/modal/noticeModal.jsx
  client/src/images/ballliston.png
  client/src/index.js
  client/src/pages/calendar/Calendar.jsx
  client/src/pages/calendar/Update.jsx
  client/src/pages/mypage/Mypage.jsx
  client/src/pages/qna/QnaDetail.jsx
  client/src/pages/qna/QnaList.jsx
  client/src/redux/action/LankAsync.jsx
  client/src/redux/action/QnaAsync.jsx
  client/src/redux/action/RecordAsync.jsx
Labels: 🌟Feature, 🏭Refactor, FrontEnd

#147 [FE]중간 Pull
  client/src/pages/qna/QnaAsk.jsx
  client/src/pages/qna/QnaDetail.jsx
  client/src/pages/qna/QnaDetailStyle.jsx
  client/src/pages/qna/QnaUpdate.jsx
  client/src/pages/qna/QnaUpdatestyle.jsx
Labels: 🌟Feature, FrontEnd

#148 [FE] 중간 pull -ko
  client/src/components/modal/Challenge.jsx
  client/src/components/modal/ChallengeReq.jsx
  client/src/pages/calendar/Calendar.jsx
  client/src/pages/calendar/Detail.jsx
  client/src/pages/calendar/Update.jsx
  client/src/pages/lank/LankContent.jsx
  client/src/pages/main/DailyCmt.jsx
  client/src/pages/main/DailyImg.jsx
  client/src/pages/main/DailyInfo.jsx
  client/src/pages/main/DailyPost.jsx
  client/src/pages/mypage/PictureBox.jsx
  client/src/pages/qna/QnaAsk.jsx
  client/src/pages/qna/QnaDetail.jsx
  client/src/redux/action/MainAsync.jsx
Labels: 🏭Refactor, FrontEnd

#150 [FE] bug-pull
  client/src/components/modal/Challenge.jsx
  client/src/pages/lank/Pagination.jsx
  client/src/pages/main/DailyInfo.jsx
  client/src/pages/qna/Pagination.jsx
  client/src/pages/qna/QnaList.jsx
Labels: 🏭Refactor, FrontEnd

#151 [FE] Err/refac- 버그수정완료
  client/src/components/modal/Challenge.jsx
  client/src/components/modal/modalstyle.jsx
  client/src/components/modal/noticeModal.jsx
  client/src/pages/calendar/Calendar.jsx
  client/src/pages/calendar/Update.jsx
  client/src/pages/lank/LankContent.jsx
  client/src/pages/lank/Pagination.jsx
  client/src/pages/main/Main.jsx
  client/src/pages/qna/QnaDetail.jsx
  client/src/pages/userprofile/index.jsx
  client/src/redux/action/LankAsync.jsx
Labels: 🖥Deploy, 🌟Feature, FrontEnd

#152 [FE] 2차오류 수정
  client/src/pages/calendar/Calendar.jsx
  client/src/pages/lank/Pagination.jsx
  client/src/pages/qna/QnaDetail.jsx
  client/src/redux/action/QnaAsync.jsx
Labels: 🤬BugFix, 🖥Deploy, FrontEnd

#153 [FE] 찐찐찐막 버그찾기
  client/src/pages/calendar/Detail.jsx
  client/src/pages/qna/QnaDetail.jsx
  client/src/redux/action/RecordAsync.jsx
Labels: 🤬BugFix, 🖥Deploy, FrontEnd

#154 [FE] 제발찐찐찐찐찐찐막
  client/src/components/modal/noticeModal.jsx
  client/src/pages/calendar/Detail.jsx
  client/src/pages/main/Main.jsx
Labels: 🤬BugFix, 🌟Feature, 🏭Refactor, FrontEnd

#130 특정 멤버 조회시 응답에 rank 추가
  server/src/main/java/com/backend/fitchallenge/domain/answer/service/AnswerService.java
  server/src/main/java/com/backend/fitchallenge/domain/member/dto/response/DetailsMemberResponse.java
  server/src/main/java/com/backend/fitchallenge/domain/member/dto/response/extract/ExtractActivity.java
  server/src/main/java/com/backend/fitchallenge/domain/member/repository/MemberRepositoryCustom.java
  server/src/main/java/com/backend/fitchallenge/domain/member/repository/MemberRepositoryImpl.java
  server/src/main/java/com/backend/fitchallenge/domain/member/service/MemberService.java
Labels: 🌟Feature, 🅱️Backend

#156 refactor : record, post, postComment 일부 수정
  server/src/main/java/com/backend/fitchallenge/domain/answer/service/AnswerService.java
  server/src/main/java/com/backend/fitchallenge/domain/post/controller/PostController.java
  server/src/main/java/com/backend/fitchallenge/domain/post/dto/PostResponse.java
  server/src/main/java/com/backend/fitchallenge/domain/postcomment/controller/CommentController.java
  server/src/main/java/com/backend/fitchallenge/domain/record/controller/RecordController.java
  server/src/main/java/com/backend/fitchallenge/domain/record/dto/request/RecordCreateVO.java
  server/src/main/java/com/backend/fitchallenge/domain/record/dto/request/RecordUpdateVO.java
Labels: 🏭Refactor, 🅱️Backend

#158 [FE] main+component+appjs url 변경
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/header/Header.jsx
  client/src/components/sidebar/Sidebar.jsx
  client/src/pages/calendar/Calendar.jsx
  client/src/pages/dailypost/DailyEdit.jsx
  client/src/pages/dailypost/dailypost.jsx
  client/src/pages/main/DailyInfo.jsx
  client/src/pages/main/DailyPost.jsx
  client/src/pages/main/Main.jsx
  client/src/pages/mypage/Mypage.jsx
  client/src/pages/mypage/PictureBox.jsx
  client/src/redux/action/MainAsync.jsx
Labels: 🏭Refactor, FrontEnd

#157 [FE] refac: uri
  client/src/pages/mypage/Mypage.jsx
  client/src/pages/profileedit/index.jsx
  client/src/pages/userprofile/index.jsx
Labels: 🚀API, FrontEnd

#160 [FE] Refac/address 라우터 주소
  client/src/pages/calendar/Calendar.jsx
  client/src/pages/calendar/Detail.jsx
  client/src/pages/calendar/Update.jsx
  client/src/pages/lank/LankContent.jsx
  client/src/pages/main/MainInside.jsx
  client/src/pages/qna/QnaList.jsx
  client/src/redux/action/LoginAsync.jsx
  client/src/redux/action/MainAsync.jsx
  client/src/redux/action/QnaAsync.jsx
  client/src/redux/action/RecordAsync.jsx
  client/src/redux/action/SignupAsync.jsx
Labels: 🚀API, 🏭Refactor

#161 [FE]root url
  client/src/App.js
  client/src/components/header/Header.jsx
  client/src/components/sidebar/Sidebar.jsx
  client/src/pages/dailypost/DailyEdit.jsx
  client/src/pages/dailypost/dailypost.jsx
  client/src/pages/mypage/Mypage.jsx
Labels: 🏭Refactor, FrontEnd

#162 [FE] Refac/address 스타일 및 리펙
  client/src/pages/lank/LankContent.jsx
  client/src/pages/lank/LankContentstyle.jsx
  client/src/pages/mypage/Mypage.jsx
  client/src/pages/qna/QnaStyle.jsx
  client/src/redux/action/LoginAsync.jsx
Labels: 🤬BugFix, 🎨CSS, 🌟Feature, FrontEnd

#163 [FE] refac/오류수정
  client/src/pages/dailypost/dailypost.jsx
  client/src/pages/lank/LankContent.jsx
  client/src/pages/lank/LankDropdown.jsx
  client/src/pages/profileedit/index.jsx
  client/src/pages/qna/QnaAsk.jsx
  client/src/redux/action/LankAsync.jsx
  client/src/redux/action/MainAsync.jsx
  client/src/redux/action/QnaAsync.jsx
Labels: 🌟Feature, 🏭Refactor, FrontEnd

#164 [FE] error/refac수정
  client/src/pages/dailypost/dailypost.jsx
  client/src/redux/action/MainAsync.jsx
Labels: 🌟Feature, 🏭Refactor, FrontEnd

#167 [FE] Main_검색엔진 완료
  client/package-lock.json
  client/package.json
  client/src/components/modal/noticeModal.jsx
  client/src/pages/calendar/Calendar.jsx
  client/src/pages/calendar/Update.jsx
  client/src/pages/main/DailyInfo.jsx
  client/src/pages/main/DailyPost.jsx
  client/src/pages/main/MainInside.jsx
  client/src/pages/main/MainStyle.jsx
  client/src/pages/profileedit/index.jsx
  client/src/pages/qna/QnaDetail.jsx
  client/src/redux/action/LankAsync.jsx
  client/src/redux/action/MainAsync.jsx
  client/src/redux/action/MypageEditAsync.jsx
  client/src/redux/action/RecordAsync.jsx
  client/src/redux/reducer/MainSlice.jsx
Labels: 🚀API, 🌟Feature, FrontEnd

#170 Q&A, Record Controller단 테스트코드 추가
  server/src/main/java/com/backend/fitchallenge/domain/answer/dto/request/AnswerCreate.java
  server/src/main/java/com/backend/fitchallenge/domain/answer/dto/request/AnswerUpdate.java
  server/src/main/java/com/backend/fitchallenge/domain/answer/dto/response/AnswerResponse.java
  server/src/main/java/com/backend/fitchallenge/domain/answercomment/dto/request/AnswerCommentCreate.java
  server/src/main/java/com/backend/fitchallenge/domain/answercomment/dto/request/AnswerCommentUpdate.java
  server/src/main/java/com/backend/fitchallenge/domain/question/dto/request/PageRequest.java
  server/src/main/java/com/backend/fitchallenge/domain/question/dto/request/QuestionCreateVO.java
  server/src/main/java/com/backend/fitchallenge/domain/question/dto/request/QuestionUpdateVO.java
  server/src/main/java/com/backend/fitchallenge/domain/question/entity/Question.java
  server/src/main/java/com/backend/fitchallenge/domain/record/controller/RecordController.java
  server/src/main/java/com/backend/fitchallenge/domain/record/dto/request/RecordCreateVO.java
  server/src/main/java/com/backend/fitchallenge/domain/record/dto/request/RecordUpdateVO.java
  server/src/test/java/com/backend/fitchallenge/controller/AnswerCommentControllerTest.java
  server/src/test/java/com/backend/fitchallenge/controller/AnswerControllerTest.java
  server/src/test/java/com/backend/fitchallenge/controller/QuestionControllerTest.java
  server/src/test/java/com/backend/fitchallenge/controller/RecordControllerTest.java
  server/src/test/java/com/backend/fitchallenge/util/QnAandRecordUtil.java
Labels: 🅱️Backend

#172 [FE] Feat/main search 검색 수정본
  client/src/pages/main/DailyPost.jsx
  client/src/pages/main/MainInside.jsx
  client/src/redux/reducer/MainSlice.jsx
Labels: 🌟Feature, 🏭Refactor, FrontEnd

#174 [FE]Feat/main act-댓글 수정, Main검색 양식 변경
  client/src/pages/calendar/Detail.jsx
  client/src/pages/calendar/Update.jsx
  client/src/pages/dailypost/DailyEdit.jsx
  client/src/pages/lank/LankContentstyle.jsx
  client/src/pages/main/DailyCmt.jsx
  client/src/pages/main/DailyInfo.jsx
  client/src/pages/main/DailyPost.jsx
  client/src/pages/main/MainInside.jsx
  client/src/pages/main/MainStyle.jsx
  client/src/pages/mypage/PictureBox.jsx
  client/src/pages/qna/QnaList.jsx
  client/src/redux/action/MainAsync.jsx
Labels: 🌟Feature, 🏭Refactor, FrontEnd

#176 [FE] Error, Refac Update
  client/public/favicon.ico
  client/src/components/header/Header.jsx
  client/src/pages/calendar/Calendar.jsx
  client/src/pages/lank/LankDropdown.jsx
  client/src/pages/main/DailyInfo.jsx
  client/src/pages/main/Main.jsx
  client/src/pages/main/MainStyle.jsx
  client/src/pages/profileedit/index.jsx
  client/src/pages/qna/QnaDetail.jsx
  client/src/pages/qna/QnaList.jsx
  client/src/pages/signup/SignUp.jsx
Labels: 🌟Feature, 🏭Refactor, FrontEnd

#179 배포완료v1.2
  client/src/pages/qna/QnaList.jsx
Labels: 🌟Feature, 🏭Refactor, FrontEnd, 🅱️Backend
